import factory from "../../support/factory"

const url = "http://localhost:3000"

const user = factory.createAuthData()

describe("auth tests", () => {
	it("toggle sign-in to sign-up", () => {
		cy.visit(`${url}/sign-up`)
		cy.contains("Sign-in").click()
		cy.url().should("equal", "http://localhost:3000/")
	})

	it("should redirect to sign-in", () => {
		cy.visit(`${url}/sign-up`)
		cy.get("#name").type(user.name)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("#confirmPassword").type(user.password)
		cy.get("button").click()
		cy.url().should("equal", "http://localhost:3000/")
	})

	it("should stay sign-up", () => {
		const user = factory.createAuthData()
		cy.visit(`${url}/sign-up`)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("#confirmPassword").type(user.password)
		cy.get("button").click()
		cy.url().should("equal", "http://localhost:3000/sign-up")
	})

	it("should stay sign-up", () => {
		const user = factory.createAuthData()
		cy.visit(`${url}/sign-up`)
		cy.get("#name").type(user.name)
		cy.get("#password").type(user.password)
		cy.get("#confirmPassword").type(user.password)
		cy.get("button").click()
		cy.url().should("equal", "http://localhost:3000/sign-up")
	})

	it("should stay sign-up", () => {
		const user = factory.createAuthData()
		cy.visit(`${url}/sign-up`)
		cy.get("#name").type(user.name)
		cy.get("#email").type(user.email)
		cy.get("#confirmPassword").type(user.password)
		cy.get("button").click()
		cy.url().should("equal", "http://localhost:3000/sign-up")
	})

	it("should stay sign-up", () => {
		const user = factory.createAuthData()
		cy.visit(`${url}/sign-up`)
		cy.get("#name").type(user.name)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.url().should("equal", "http://localhost:3000/sign-up")
	})

	it("toggle sign-in to sign-up", () => {
		cy.visit(url)
		cy.contains("Sign-up").click()
		cy.url().should("equal", "http://localhost:3000/sign-up")
	})
	
	it("should redirect to home sucessfull login", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.url().should("equal", "http://localhost:3000/home")
	})
})

describe("select level quiz tests", () => {
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#flags-easy").click()
		cy.get("#title").contains("what is the flags")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#flags-medium").click()
		cy.get("#title").contains("what is the flags")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#flags-hard").click()
		cy.get("#title").contains("what is the flags")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#capitals-easy").click()
		cy.get("#title").contains("what is the capitals")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#capitals-medium").click()
		cy.get("#title").contains("what is the capitals")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#capitals-hard").click()
		cy.get("#title").contains("what is the capitals")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#territories-easy").click()
		cy.get("#title").contains("what is the territories")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#territories-medium").click()
		cy.get("#title").contains("what is the territories")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
	it("should redirect to correct option quiz", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		cy.get("#territories-hard").click()
		cy.get("#title").contains("what is the territories")
		cy.url().should("equal", "http://localhost:3000/quiz")
	})
})

describe("select an option quiz test", () => {
	it("should register answers, show result and back to home", () => {
		cy.visit(url)
		cy.get("#email").type(user.email)
		cy.get("#password").type(user.password)
		cy.get("button").click()
		const option = factory.createLevel()
		cy.get(option).click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get(".single-option").first().click()
		cy.get("#result").contains("you got it right")
		cy.get("#finish").click()
		cy.url().should("equal", "http://localhost:3000/home")
	})
})